### ISSUE TITLE
第一集的development应该翻译为“发展”呢还是“开发”呢

### ISSUE THREAD

**Issue by yy35959199** [mayf09/6.824-2021-video-subtitles#48]
上下文的几个development都是，比如这一句：
00:14:54,480 --> 00:15:01,170
Now you know just like completely booming research field and development field.

翻译为：
00:14:54,480 --> 00:15:01,170
现在你知道，它在研究领域和发展领域一样蓬勃发展。

“发展领域”听起来有点怪怪的……如果是“开发”的话，大概就是研究（理论）和开发（实践）对应的感觉？
（英语不好OTZ但读这句的时候“发展领域”没读懂……感觉可能想表达的是个理论和实践的关系？）

**Comment by mayf09** [comment]
有道理。已经修改
